"""HTML report generation for ONNX models."""

from onnx import ModelProto
from ..core.model_loader import (
    model_summary,
    list_nodes,
    list_inputs,
    list_outputs,
    list_initializers,
)
from .flops import estimate_flops, format_flops, format_params
import json


def _shape_str(s):
    """Convert a shape list to a display string."""
    return "x".join(str(d) for d in s) if s else "scalar"


def generate_html_report(model: ModelProto, title: str = "ONNX Model Report") -> str:
    """Generate a standalone HTML report for an ONNX model.

    Args:
        model: The ONNX model to report on.
        title: Page title.

    Returns:
        Complete HTML string (self-contained, no external deps).
    """
    summary = model_summary(model)
    nodes = list_nodes(model)
    inputs = list_inputs(model)
    outputs = list_outputs(model)
    inits = list_initializers(model)
    flops_data = estimate_flops(model)

    # Graph as JSON for visualization
    _graph_to_json(model)

    # Build parameter rows using helper to avoid quote conflicts
    param_rows = ""
    for init in inits[:50]:
        param_rows += (
            f"<tr><td>{init['name'][:40]}</td>"
            f"<td>{init['dtype']}</td>"
            f"<td>{_shape_str(init['shape'])}</td>"
            f"<td>{init['size_bytes'] // 4} params</td></tr>"
        )

    html = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<title>{title}</title>\n"
        "<style>\n"
        "  * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        '  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;\n'
        "         background: #f5f7fa; color: #1a1a2e; line-height: 1.6; }\n"
        "  .container { max-width: 960px; margin: 0 auto; padding: 20px; }\n"
        "  h1 { font-size: 1.8rem; margin-bottom: 8px; }\n"
        "  h2 { font-size: 1.3rem; margin: 24px 0 12px; padding-bottom: 6px;\n"
        "         border-bottom: 2px solid #e0e0e0; }\n"
        "  .subtitle { color: #666; margin-bottom: 20px; }\n"
        "  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n"
        "          gap: 12px; margin-bottom: 20px; }\n"
        "  .card { background: white; border-radius: 8px; padding: 16px; box-shadow: 0 1px 3px rgba(0,0,0,.08); }\n"
        "  .card .label { font-size: .75rem; text-transform: uppercase; color: #888; letter-spacing: .05em; }\n"
        "  .card .value { font-size: 1.5rem; font-weight: 700; color: #1a1a2e; }\n"
        "  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px;\n"
        "          overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.08); }\n"
        "  th { background: #1a1a2e; color: white; padding: 10px 12px; text-align: left;\n"
        "        font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; }\n"
        "  td { padding: 8px 12px; border-bottom: 1px solid #eee; font-size: .9rem; }\n"
        "  tr:hover { background: #f8f9ff; }\n"
        "  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px;\n"
        "            font-size: .75rem; font-weight: 600; }\n"
        "  .badge-blue { background: #e3f2fd; color: #1565c0; }\n"
        "  .badge-green { background: #e8f5e9; color: #2e7d32; }\n"
        "  .op-list { display: flex; flex-wrap: wrap; gap: 6px; }\n"
        "  .op-tag { background: #e3f2fd; color: #1565c0; padding: 4px 10px; border-radius: 12px;\n"
        "            font-size: .8rem; }\n"
        "  .graph-viz { background: #1a1a2e; color: #e0e0e0; padding: 20px; border-radius: 8px;\n"
        '               font-family: "Courier New", monospace; font-size: .8rem; white-space: pre;\n'
        "               overflow-x: auto; }\n"
        "  .footer { margin-top: 30px; padding: 16px; text-align: center; color: #888; font-size: .8rem; }\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        '<div class="container">\n'
        f"<h1>{title}</h1>\n"
        '<p class="subtitle">Generated by ONNX Model Surgery</p>\n'
        '<div class="grid">\n'
        f'  <div class="card"><div class="label">Graph Name</div><div class="value">{summary["graph_name"] or "unnamed"}</div></div>\n'
        f'  <div class="card"><div class="label">Nodes</div><div class="value">{summary["node_count"]}</div></div>\n'
        f'  <div class="card"><div class="label">Parameters</div><div class="value">{format_params(flops_data["total_params"])}</div></div>\n'
        f'  <div class="card"><div class="label">FLOPs</div><div class="value">{format_flops(flops_data["total_flops"])}</div></div>\n'
        f'  <div class="card"><div class="label">Inputs</div><div class="value">{summary["input_count"]}</div></div>\n'
        f'  <div class="card"><div class="label">Outputs</div><div class="value">{summary["output_count"]}</div></div>\n'
        "</div>\n"
        "<h2>Operator Types</h2>\n"
        '<div class="op-list">\n'
        + "".join(
            f'<span class="op-tag">{op}</span>' for op in sorted(summary["op_types"])
        )
        + "\n</div>\n"
        "<h2>Inputs / Outputs</h2>\n"
        "<table>\n"
        "<tr><th>Name</th><th>Direction</th><th>Shape</th><th>Dtype</th></tr>\n"
        + "".join(
            f'<tr><td>{i["name"]}</td><td><span class="badge badge-blue">input</span></td><td>{i.get("shape")}</td><td>{i.get("dtype")}</td></tr>'
            for i in inputs
        )
        + "".join(
            f'<tr><td>{o["name"]}</td><td><span class="badge badge-green">output</span></td><td>{o.get("shape")}</td><td>{o.get("dtype")}</td></tr>'
            for o in outputs
        )
        + "</table>\n"
        f"<h2>Node List ({len(nodes)})</h2>\n"
        "<table>\n"
        "<tr><th>#</th><th>Name</th><th>Op Type</th><th>Inputs</th><th>Outputs</th></tr>\n"
        + "".join(
            f'<tr><td>{i}</td><td>{n["name"]}</td><td><span class="badge badge-blue">{n["op_type"]}</span></td><td>{", ".join(n["inputs"][:3])}</td><td>{", ".join(n["outputs"][:2])}</td></tr>'
            for i, n in enumerate(nodes[:200])
        )
        + "</table>\n"
        "<h2>FLOPs Breakdown</h2>\n"
        "<table>\n"
        "<tr><th>Op Type</th><th>FLOPs</th></tr>\n"
        + "".join(
            f"<tr><td>{op}</td><td>{format_flops(flops)}</td></tr>"
            for op, flops in sorted(
                flops_data["flops_by_op"].items(), key=lambda x: -x[1]
            )
        )
        + "</table>\n"
        "<h2>Parameters</h2>\n"
        "<table>\n"
        "<tr><th>Name</th><th>Dtype</th><th>Shape</th><th>Size</th></tr>\n"
        + param_rows
        + "</table>\n"
        '<div class="footer">\n'
        f"  Generated by <strong>ONNX Model Surgery</strong> &mdash; {summary['producer_name']} v{summary['producer_version']}\n"
        "</div>\n"
        "</div>\n"
        "</body>\n"
        "</html>"
    )
    return html


def _graph_to_json(model: ModelProto) -> str:
    """Convert model graph to JSON."""
    data = {
        "nodes": [],
        "edges": [],
    }
    for i, n in enumerate(model.graph.node):
        node_id = n.name or f"node_{i}"
        data["nodes"].append(
            {
                "id": node_id,
                "op_type": n.op_type,
                "index": i,
            }
        )
        for inp in n.input:
            if inp:
                data["edges"].append({"from": inp, "to": node_id})
    return json.dumps(data, indent=2)
